export const ADD_COMMENT= 'ADD_COMMENT';
export const DEL_COMMENT= 'DEL_COMMENT';

export const DISH_LOADING = 'DISH_LOADING';
export const DISH_FAILED = 'DISH_FAILED';
export const ADD_DISHES = 'ADD_DISHES';

export const ADD_LEADERS ='ADD_LEADERS';
export const LEADERS_FAILED ='LEADERS_FAILED';
export const LEADERS_LOADING ='LEADERS_LOADING';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';

